name: CI

on:
  push:
    branches:
    - mkdocs

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: test
      run: npx lint-md-cli *.md

    - name: build docs to HTML
      run: | 
        sudo apt-get update
        sudo apt-get install -y python3-pip
        sudo -H pip install mkdocs
        ./build-docs.sh

    - name: deploy to gh-pages
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: master
        build_dir: site
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
